version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws
    environment:
      - ENVIRONMENT=development # docker-compose での時は開発モードを有効にする


